name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  push_to_replicate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push to Replicate
        run: cog push r8.im/veaceslavsorici-del/autotube-render-model
